name: 'Build Size Cache'
description: 'Caches build size'
author: 'superdispatch'
inputs:
  dir:
    required: true
    description: 'path to the build folder'

  hash-pattern:
    required: false
    default: '/.([a-f0-9])+./'
    description: 'regex pattern to detect hash part of file name'

  hash-placeholder:
    required: false
    default: '.[hash].'
    description: 'string to replace hash part of file name'

  sha:
    required: true
    default: '${{ github.event.pull_request.base.sha }}'
    description: 'commit sha'

  label:
    required: true
    default: 'default'
    description: 'custom label to distinguish multiple builds'

  pr:
    required: true
    default: '${{ github.event.number }}'
    description: 'pull request number'

  token:
    required: true
    default: '${{ github.token }}'
    description: 'github token'

runs:
  using: 'node16'
  main: 'dist/index.js'
