name: 'Prepare Node package repository'
description: 'Setup and prepare Node package repository'
author: 'superdispatch'

inputs:
  working-directory:
    required: false
    default: '${{ github.workspace }}'
    description: 'The default working directory'

  node-version:
    required: false
    default: 'lts/*'
    description: 'Node version specifier.'

  cache-key:
    required: false
    description: 'An explicit key for restoring and saving the cache'

runs:
  using: 'composite'
  steps:
    - name: 'Disable automatic line-end conversion'
      shell: bash
      run: git config --global core.autocrlf false

    - name: 'Checking out the repository'
      uses: actions/checkout@v3

    - name: 'Setting up Node'
      uses: buildjet/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}
        cache-dependency-path: ${{ inputs.package-manager-dependency-path }}

    - name: 'Installing dependencies'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm i

    - name: Cache node modules
      uses: buildjet/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ inputs.cache-key || runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ inputs.cache-key || runner.os }}-build-${{ env.cache-name }}-
          ${{ inputs.cache-key || runner.os }}-build-
          ${{ inputs.cache-key || runner.os }}-
