name: 'Sync issue with PR'
description: 'Updates PR details for JIRA issue'
author: 'superdispatch'

inputs:
  token:
    required: true
    default: '${{ github.token }}'
    description: 'github token'

  issue-placeholder:
    description: 'Issue placeholder text in PR body'
    required: false
    default: '<!--ISSUE_LINK-->'

  jira-namespace:
    description: 'JIRA namespace'
    required: true

outputs:
  issue:
    description: 'JIRA Issue number'

runs:
  using: 'node12'
  main: 'dist/index.js'
