name: 'Sync issue with PR'
description: 'Updates PR details for JIRA issue'
author: 'superdispatch'

inputs:
  token:
    required: true
    default: '${{ github.token }}'
    description: 'github token'

outputs:
  issue:
    description: 'JIRA Issue number'

runs:
  using: 'node16'
  main: 'dist/index.js'
