name: 'Deploy Preview'
description: 'Deploy preview to Netlify'
author: 'superdispatch'
inputs:
  dir:
    required: true
    description: 'folder to deploy'

  alias:
    required: false
    description: 'alias for deployment'

  pr:
    required: true
    default: '${{ github.event.number }}'
    description: 'pull request number'

  token:
    required: true
    default: '${{ github.token }}'
    description: 'github token'

  netlify-token:
    required: true
    description: 'netlify token'

  netlify-site-id:
    required: true
    description: 'netlify site to deploy to'

runs:
  using: 'node20'
  main: 'dist/index.js'
