name: Checks

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/prepare-node-repo@main
        with:
          node-version: 24
      - run: pnpm tsc
      - run: pnpm lint
      - run: pnpm build --verify
