name: PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./prepare-node-repo@main
        with:
          node-version: 20
      - run: yarn tsc
      - run: yarn lint
      - uses: superdispatch/actions/update-snapshots@v1.5.0
        with:
          command: yarn build --verify
          update-command: yarn build
