name: PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          node-version: 18
      - run: yarn tsc
      - run: yarn lint
      - uses: superdispatch/actions/update-snapshots@v1.5.0
        with:
          command: yarn build --verify
          update-command: yarn build
